export enum ApiError {
    NO_MORE_LIFE = "NO_MORE_LIFE",
    MISSING_OR_INVALID_TOKEN = "MISSING_OR_INVALID_TOKEN",
    USER_ALREADY_CREATED = "USER_ALREADY_CREATED",
    BET_ALREADY_PLACED = "BET_ALREADY_PLACED"
}